### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by paaljoachim** [humanmade/disable-accounts#5]
WordPress 5.8.
Multisite.

The following error message is seen upon activation.

Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Call to undefined function Altis\register_class_path() in /home/easywebd/public_html/dev/mytestingbox.com/wp-content/plugins/disable-accounts-main/plugin.php:12 Stack trace: #0 /home/easywebd/public_html/dev/mytestingbox.com/wp-admin/includes/plugin.php(2286): include_once() #1 /home/easywebd/public_html/dev/mytestingbox.com/wp-admin/plugins.php(191): plugin_sandbox_scrape('disable-account...') #2 {main} thrown in /home/easywebd/public_html/dev/mytestingbox.com/wp-content/plugins/disable-accounts-main/plugin.php on line 12

**Comment by ntwb** [comment]
Thanks @paaljoachim this plugin is designed to be used with Altis from HM https://www.altis-dxp.com/

With that said, all the Altis CMS modules are open source and can be seen here:

https://github.com/orgs/humanmade/repositories?q=altis&type=source&language=&sort=name

Finally, this plugin has only that single Altis dependency, so if you comment out line 12 I think the plugin should run fine on any network install.

https://github.com/humanmade/disable-accounts/blob/main/plugin.php#L12

**Comment by rmccue** [comment]
We can replace this with the Composer autoload if we're publishing there

**Comment by tomjn** [comment]
We should mention Altis and at least `composer install` in the readme's install step

**Comment by kasparsd** [comment]
Considering that `./inc` doesn't actually contain any classes (as required by `\Altis\register_class_path()`), it looks like removing the `\Altis\register_class_path()` is enough. There are no classes that would need autoloading at the moment.

I've created #8 as a fix.

**Comment by kasparsd** [comment]
Thanks! 

Would it be possible to tag a release with this change so that Packagist picks it up?

**Comment by rmccue** [comment]
0.2.2 is now tagged :)
